### ISSUE TITLE
Horizontal Timeline up and down

### ISSUE THREAD

**Issue by khawar512** [GjjvdBurg/labella.py#16]
Dear @GjjvdBurg,

Thank you for your work. I see your timeline and do you have a horizontal timeline with up and down features. I mean that we can write on both sides. At this moment, I checked your examples files in which we can only write on up or down sides.

Regards,
Khawar

**Comment by GjjvdBurg** [comment]
Hi @khawar512, thanks for raising this issue. At the moment this is not something I'm looking to support as it would mean rewriting a significant part of the layout logic. If you'd like to try implementing it yourself, you'd essentially need a version of the overlap algorithm that instead of moving the nodes up a layer, moves them to a layer on the opposite side of the figure. Good luck!
